### ISSUE TITLE
Can't break fu door

### ISSUE THREAD

**Issue by Snownee** [TeamCovertDragon/SpringFestival#7]
```
[18:26:08] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@6248827e:
java.lang.NullPointerException: null
	at team.covertdragon.springfestival.module.decoration.TileFuDoor.getOriginalDoor(TileFuDoor.java:27) ~[TileFuDoor.class:?]
	at team.covertdragon.springfestival.module.decoration.BlockFuDoor.harvestBlock(BlockFuDoor.java:136) ~[BlockFuDoor.class:?]
	at team.covertdragon.springfestival.module.decoration.ModuleDecoration.onBlockBreak(ModuleDecoration.java:91) ~[ModuleDecoration.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_ModuleDecoration_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:822) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:309) [PlayerInteractionManager.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:171) [PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:719) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:56) [CPacketPlayerDigging.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:12) [CPacketPlayerDigging.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:53) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[18:26:08] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[18:26:08] [Server thread/ERROR] [FML]: 0: NORMAL
[18:26:08] [Server thread/ERROR] [FML]: 1: ASM: team.covertdragon.springfestival.module.decoration.ModuleDecoration@95aa79c onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[18:26:08] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at team.covertdragon.springfestival.module.decoration.TileFuDoor.getOriginalDoor(TileFuDoor.java:27) ~[TileFuDoor.class:?]
	at team.covertdragon.springfestival.module.decoration.BlockFuDoor.harvestBlock(BlockFuDoor.java:136) ~[BlockFuDoor.class:?]
	at team.covertdragon.springfestival.module.decoration.ModuleDecoration.onBlockBreak(ModuleDecoration.java:91) ~[ModuleDecoration.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_ModuleDecoration_onBlockBreak_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:822) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:309) ~[PlayerInteractionManager.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:171) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:719) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:56) ~[CPacketPlayerDigging.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:12) ~[CPacketPlayerDigging.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
```

**Comment by SeraphJACK** [comment]
正常情况贴red paper出来的fu door是不会有这个问题的，你这里的fu door应该是创造模式拿的，等我待会去加个null protection(
